**Author: Amey Sunil Sadegaonkar
Project: Book Reccommendation System**

- This Notebook is Part of abovementioned Project
- Following are the Objectives for this Notebook

## Objectives: 

- Get Book Title from Partial name : basically a search facility
- Get Top 20 Recommended books based on popularity
    - Calculate popularity based on weighted rating formula

=========================================================================================================================

### Necessary Libraries and Modules

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### Loading Books Dataset (cleaned)

In [2]:
books= pd.read_csv("C:\\Users\\ameys\\Desktop\\CDAC\\69618_amey\\CDAC_Project\\project_books_reco\\BooksData_cleaned_RecSys.csv")

In [3]:
books.sample(10)

,BookID,BookTitle,Authors,Language,AverageRating,1StarRatingCount,2StarRatingCount,3StarRatingCount,4StarRatingCount,5StarRatingCount,TotalRatingCount,PageCount,Publisher,PublishYear,Description
69100,804455,The Penguin Dictionary of Saints,Donald Attwater,eng,3.61,1,1,15,9,7,33,352,Puffin,1984-01-01,The Penguin Dictionary of Saints
4209,22072,"The War of the Worlds Murder (Disaster Series,...",Max Allan Collins,eng,3.71,9,15,97,107,68,296,256,Berkley,2005-01-01,"The War of the Worlds Murder (Disaster Series,..."
164848,4838386,The Popper-Carnap Controversy,Alex C. Michalos,eng,0.00,0,0,0,0,0,0,124,Springer,1971-01-01,1 In 1954 Karl Popper published an article att...
129725,2431516,The Guide To Understanding The Insurance Indus...,Chris Sharkey,eng,1.00,1,0,0,0,0,1,60,BookSurge Publishing,2007-01-01,"""The Guide to Understanding the Insurance Indu..."
78247,950498,Legacy of the Night Warrior,Stephen K. Hayes,eng,3.94,2,4,14,23,24,67,192,Black Belt Communications,1984-01-01,Heading further down the warrior’s path while ...
29880,245113,"Father, Son & Co.",Thomas J. Watson Jr.,eng,4.11,3,5,61,154,118,341,544,Bantam,1991-01-01,"Father, Son & Co."
7151,39916,Epileptic,David B.,eng,3.88,385,1014,2774,4100,4423,12696,368,Pantheon,2005-01-01,Epileptic
103354,1535065,A Family Likeness,Margot Dalton,eng,3.54,0,1,5,6,1,13,304,Harlequin Superromance,1996-01-01,"\n ""Margot Dalton's creativity dazzles…"" —Bet..."
155923,3724526,Darcy's Passions: Pride and Prejudice Retold T...,Regina Jeffers,eng,3.60,82,165,440,455,399,1541,386,CreateSpace Independent Publishing Platform,2017-01-01,"Witty, romantic and insightful, Darcy’s Passio..."
93743,1272503,Hitler's Banker: Hjalmar Horace Greeley Schacht,John Weitz,eng,3.50,0,4,9,9,4,26,384,Warner Futura,2002-01-01,"A biography of Hjalmar Schacht, Chief Architec..."

=========================================================================================================================

### 1.0. Getting "BookTitle" from Partial Name

- Not everyone can remember the exact name of book nor they know what was listed name of that book in our dataset so we are going to use the function which can search the name of books which contain the partial name in it.

In [4]:
# List of all book Titles
all_books_titles = list(books.BookTitle.values)

In [5]:
# Function to get Books containing partial name

def BookTitles_from_partialTitle(partial):
    for name in all_books_titles:
        if partial in name:
            print(name)

- Examples of uses of the function
    - Harry Potter Books
    - Book Title Containing word "birds"
    - Book Titles Containing word "mathematics"
    - Book Titles Containing words "Narnia"

In [6]:
BookTitles_from_partialTitle("Harry Potter")

Harry Potter and the Half-Blood Prince (Harry Potter, #6)
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Harry Potter and the Sorcerer's Stone (Harry Potter, #1)
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)
Harry Potter and the Goblet of Fire (Harry Potter, #4)
Harry Potter Boxed Set, Books 1-5 (Harry Potter, #1-5)
Harry Potter Collection (Harry Potter, #1-6)
Harry Potter Schoolbooks Box Set: Two Classic Books from the Library of Hogwarts School of Witchcraft and Wizardry
J.K. Rowling's Harry Potter Novels: A Reader's Guide
Harry Potter and the Philosopher's Stone
Looking for God in Harry Potter
Harry Potter and Philosophy: If Aristotle Ran Hogwarts
Harry Potter Boxed Set (Harry Potter, #1-4)
Mapping the World of Harry Potter: Science Fiction and Fantasy Writers Explore the Bestselling Series of All Time
Harry Potter and the Half-blood Prince (Harry Potter, #6)
Harry Potter and the Deathly Hallows (Harry Potter, #7)
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Harry Potter and the Sorcerer's Stone
Harry Potter and the Half-Blood Prince (Harry Potter, #6)
The Harry Potter Collection 1-4 (Harry Potter, #1-4)
Harry Potter and the Order of the Phoenix
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Muggles and Magic: An Unofficial Guide to J.K. Rowling and the Harry Potter Phenomenon
What's a Christian to Do with Harry Potter?
Harry Potter and the Deathly Hallows (Harry Potter, #7)
Harry Potter and the Half-Blood Prince (Harry Potter, #6)
Harry Potter and the Philosopher's Stone (Harry Potter, #1)
Sticks and Stones: The Troublesome Success of Children's Literature from Slovenly Peter to Harry Potter
Harry Potter and the Sorcerer's Stone (Harry Potter, #1)
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Muggles and Magic: J. K. Rowling and the Harry Potter Phenomenon
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Harry Potter and the Half-Blood Prince (Harry Potter, #6)
Harry Potter Boxed Set (Harry Potter, #1-6)
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Harry Potter and the Deathly Hallows (Harry Potter, #7)
Harry Potter and the Philosopher's Stone
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Harry Potter and the Chamber of Secrets
Harry Potter and the Half-Blood Prince (Harry Potter, #6)
Harry Potter and the Philosopher's Stone (Harry Potter, #1)
Harry Potter and the Order of the Phoenix
Harry Potter and the Goblet of Fire (Harry Potter, #4)
Harry Potter and the Deathly Hallows (Harry Potter, #7)
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
From Alice to Harry Potter: Children's Fantasy in England
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Storybook Travels: From Eloise's New York to Harry Potter's London, Visits to 30 of the Best-Loved Landmarks in Children's Literature
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)
Harry Potter and the Philosopher's Stone (Harry Potter, #1)
JK Rowling: the wizard behind Harry Potter
Harry Potter and the Chamber of Secrets (Harry Potter, #2)
Mugglenet.com's Harry Potter Companion
Harry Potter and the Order of the Phoenix (Harry Potter, #5)
Harry Potter and the Philosopher's Stone (Harry Potter, #1)
Harry Potter Box Set (Harry Potter, #1-4)
Hogwarts Through The Years (Harry Potter Poster Book)
The Unauthorised Harry Potter Companion
The Magical World Of Harry Potter: The Unauthorised Guide To The Adventures Of Harry Potter
Children's Literature: A Reader's History, from Aesop to Harry Potter
Harry Potter and the Prisoner of Azkaban
Harry, a History: The True Story of a Boy Wizard, His Fans, and Life Inside the Harry Potter Phenomenon
Phoenix Rising: Collected Papers on Harry Potter, 17-21 May 2007
Harry Potter Adult Boxed Set (Harry Potter, #1-7)

In [7]:
BookTitles_from_partialTitle("birds")

Four & Twenty Blackbirds (Bardic Voices, #4)
Nightbirds on Nantucket (The Wolves Chronicles, #3)
Firebirds: An Anthology of Original Fantasy and Science Fiction
Firebirds Rising: An Anthology of Original Science Fiction and Fantasy
Firebirds: An Anthology of Original Fantasy and Science Fiction
Season of the Rainbirds
Season Of The Rainbirds
The Wind Birds: Shorebirds of North America
Firebirds
Blackbirds at the Gallop
Field Guide to Seabirds of the World
Lovebirds
Thunderbirds: The Making of the Movie
Carving Hummingbirds
Lovebirds / Love by the Book / One Boy Too Many (Sweet Dreams Collection)
How to talk to the birds and the beasts : by their body language & their sounds you shall know them
Hunting Warbirds: The Obsessive Quest for the Lost Aircraft of World War II
Field Guide to New Zealand Seabirds

In [8]:
BookTitles_from_partialTitle("mathematics")

London GCSE mathematics. Non-calculator practice pack.

In [9]:
BookTitles_from_partialTitle("Narnia")

The Chronicles of Narnia (Chronicles of Narnia, #1-7)
The Chronicles of Narnia: Including an Essay on Writing by C.S. Lewis
The Chronicles of Narnia (The Chronicles of Narnia, #1-7)
The Collected Letters of C.S. Lewis, Volume 3: Narnia, Cambridge, and Joy, 1950 - 1963
The Voyage of the “Dawn Treader” (The Chronicles of Narnia, #3)
Prince Caspian (Chronicles of Narnia, #4)
The Lion, the Witch and the Wardrobe (Chronicles of Narnia #2)
Finding God in the Land of Narnia
The Magician's Nephew (Chronicles of Narnia, #6)
The Horse and His Boy (Chronicles of Narnia, #3)
The Magician's Nephew (Chronicles of Narnia, #1)
The Silver Chair (Chronicles of Narnia, #4)
The Lion, the Witch and the Wardrobe (The Chronicles of Narnia, #2)
The Voyage of the Dawn Treader (Chronicles of Narnia, #5)
The Last Battle (Chronicles of Narnia, #7)
The Last Battle (Chronicles of Narnia, #7)
The Chronicles of Narnia: The Lion, The Witch and The Wardrobe Official Strategy Guide
The Keys to the Chronicles: Unlocking the Symbols of C. S. Lewis's Narnia
From Narnia to a Space Odyssey: The War of Ideas Between Arthur C. Clarke and C.S. Lewis
Narnia and Beyond: A Guide to the Fiction of C. S. Lewis
Prince Caspian (Chronicles of Narnia, #2)
Cameras in Narnia: How The Lion, The Witch and The Wardrobe Came to Life
The Voyage of the Dawn Treader (Chronicles of Narnia, #3)
The Voyage of the Dawn Treader (The Chronicles of Narnia)
The Voyage of the Dawn Treader (Chronicles of Narnia)
The Last Battle (Chronicles of Narnia, #7)
The Magician's Nephew (Chronicles of Narnia, #1)
The Horse and His Boy (Chronicles of Narnia, #3)
Prince Caspian (Chronicles of Narnia, #4)
The Lion, the Witch and the Wardrobe (Chronicles of Narnia, #2)
Into the Wardrobe: C. S. Lewis and the Narnia Chronicles
The Narnia Cookbook: Foods from C. S. Lewis's The Chronicles of Narnia
Prince Caspian (The Chronicles of Narnia, #2)
The Silver Chair (The Chronicles of Narnia, #4)
The Horse and His Boy (The Chronicles of Narnia, #5)
La dernière bataille (Les Chroniques de Narnia, #7)
The Voyage of the Dawn Treader (The Chronicles of Narnia, #3)
The Chronicles of Narnia (The Chronicles of Narnia, #1-7)
Prince Caspian (Chronicles of Narnia, #4)
Le fauteuil d'argent (Les Chroniques de Narnia, #6)
The Magician's Nephew (The Chronicles of Narnia, #6)
The Voyage of the Dawn Treader (Chronicles of Narnia, 5)
The Last Battle (Chronicles of Narnia, #7)
The Horse and His Boy (The Chronicles of Narnia, #3)
The Silver Chair (The Chronicles of Narnia, #6)
The Last Battle (The Chronicles of Narnia, #7)
The Lion, The Witch and the Wardrobe  (Chronicles of Narnia, #2)
The Magician's Nephew (Chronicles of Narnia, #1)
The Chronicles of Narnia Box Set
The Lion, the Witch and the Wardrobe (The Chronicles of Narnia, #2)
The Horse and His Boy  (Chronicles of Narnia, #3)
The Chronicles Of Narnia: Boxed Set (The Chronicles Of Narnia)
Prince Caspian (The Chronicles of Narnia, #4)
The Magician's Nephew (The Chronicles of Narnia)
The Voyage of the Dawn Treader (The Chronicles of Narnia, #3)
The Voyage of the Dawn Treader (The Chronicles of Narnia)
The Voyage of the Dawn Treader (Chronicles of Narnia (chronological), #5) (Chronicles of Narnia, #3)
The Magician's Nephew (Chronicles of Narnia)
The Silver Chair (Chronicles of Narnia, #6)
The Last Battle (Chronicles of Narnia, #7)
The Silver Chair (The Chronicles of Narnia, #4)
The Magician's Nephew (The Chronicles of Narnia #1)
The Silver Chair (Chronicles of Narnia, #6)
The Soul of Prince Caspian: Exploring Spiritual Truth in the Land of Narnia
Planet Narnia: The Seven Heavens in the Imagination of C.S. Lewis
The Horse and His Boy (Chronicles of Narnia, #3)
The Lion, the Witch and the Wardrobe (Chronicles of Narnia, #2)
The chronicles of Narnia
The Chronicles of Narnia
Boxen: Childhood Chronicles Before Narnia
Narnia and the Fields of Arbol: The Environmental Vision of C.S. Lewis

In [10]:
BookTitles_from_partialTitle("Hobbit")

J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings
The Hobbit, or There and Back Again
The Annotated Hobbit
Poems From The Hobbit
The Hobbit: Or There and Back Again
The Lord of the Rings / The Hobbit
The Hobbit, or, There and Back Again
The Hobbit or There and Back Again (Thorndike Press Large Print Basic Series)
The Hobbit, Mr Baggins and The Return to Bag-End: Boxed Set
The Hobbit
The Hobbit / The Lord of the Rings
The Hobbit (Middle-Earth Universe)
The Hobbit, or There and Back Again
The Complete Guide to Middle Earth: From The Hobbit to The Silmarillion
The History of the Hobbit, Part One: Mr. Baggins
The Hobbit: Graphic Novel
The Annotated Hobbit (Middle-earth Universe)
The Hobbit
The Complete Guide to Middle-Earth: From the Hobbit Through the Lord of the Rings and Beyond
The History of the Hobbit, Part Two: Return to Bag-End
The Hobbit & The Lord of the Rings (Slipcased Set)
The Hobbit: or There and Back Again
The Hobbit Or, There and Back Again
The Annotated Hobbit
The Hobbit and The Lord of the Rings
The Hobbit, Mr Baggins and the Return to Bag-End: Boxed Set
The History of the Hobbit, Part One: Mr. Baggins
The Hobbit
The Hobbit
The History of the Hobbit, Part One: Mr. Baggins
The Hobbit
The Hobbit: The Enchanting Prelude To The Lord Of The Rings
The Hobbit Or There And Back Again
Hobbitten
A Hobbit's Journal: Being A Blank Book with Some Curious Illustrations of Friends and Foes of the Nine Companions

========================================================================================================================

### 2.0 Get Top 20 Recommended books based on popularity

- In **popularity based approach** of recommendation system, we can check about the books which are in trend or are most popular among the users and directly recommend them.
- We will be showing Top 20 Recommended books based on popularity index which is calcuted using Weighted Rating formula

- WR = [(v * R)/(v + m)] + [(m * c)/(v + m)]
    
    where,
    v is the number of votes for the books;
    
    m is the minimum votes required to be listed in the chart;
    
    R is the average rating of the book; and
    
    C is the mean vote across the whole report.

In [11]:
ratings = books["AverageRating"]
rating_count = books["TotalRatingCount"]
MR = ratings.convert_dtypes(np.float16).mean()
print("Mean Rating (MR) accross all books: ", MR)

q = rating_count.quantile(0.99)
print("Minimum number of required ratings (q): ", q)

Mean Rating (MR) accross all books:  3.7339116382577475
Minimum number of required ratings (q):  246110.4400000004

In [12]:
# our weighted rating algorithm
def weighted_rating(books):
    v = books['TotalRatingCount']
    R = books['AverageRating']
    return (v/(v+q) * R) + (q/(q+v) * MR)

In [13]:
books.shape

(164913, 15)

In [14]:
top_books = books[(books["TotalRatingCount"] >= q) & (books["AverageRating"] > MR)]
top_books.shape

(1553, 15)

In [15]:
top_books["weighted"] = top_books.apply(weighted_rating, axis=1)
above_average = top_books.sort_values("weighted", ascending=False)
above_average.shape

(1553, 16)

In [16]:
above_average.sample(20)

,BookID,BookTitle,Authors,Language,AverageRating,1StarRatingCount,2StarRatingCount,3StarRatingCount,4StarRatingCount,5StarRatingCount,TotalRatingCount,PageCount,Publisher,PublishYear,Description,weighted
63811,712998,The Handmaid's Tale,Margaret Atwood,eng,4.11,30870,60948,216380,490432,581991,1380621,324,Virago,1990-01-01,The Republic of Gilead allows Offred only one ...,4.053101
119975,2075584,The Tragedie of Romeo & Juliet,William Shakespeare,eng,3.75,71760,182817,540456,628330,608233,2031596,238,Hyperion Books,1990-01-01,"In Romeo and Juliet, Shakespeare creates a wor...",3.748262
81259,1004145,The Strange Case of Dr Jekyll and Mr Hyde,Robert Louis Stevenson,eng,3.81,4716,21932,104063,142092,93518,366321,88,Penguin,2006-01-01,Everyone has a dark side. Dr Jekyll has discov...,3.779423
70532,825248,"The Two Towers (The Lord of the Rings, #2)",J.R.R. Tolkien,eng,4.44,4148,12437,66797,195344,410552,689278,335,Houghton Mifflin Company,2002-01-01,The standard hardcover edition of the second v...,4.254221
150283,3335396,Sense And Sensibility,Jane Austen,eng,4.07,22108,41146,169502,331404,388294,952454,584,ReadHowYouWant,2008-01-01,"'The more I know of the world, the more am I c...",4.000988
150683,3357182,The Call Of The Wild,Jack London,eng,3.87,8258,21023,80710,122766,105270,338027,76,Kessinger Publishing,2004-01-01,"First published in 1903, The Call of the Wild ...",3.812663
26373,208715,Persuasion,Jane Austen,eng,4.14,9274,19448,85966,163740,221919,500347,254,Penguin,1994-01-01,Persuasion,4.006111
1214,5759,Fight Club,Chuck Palahniuk,eng,4.19,6089,15954,70345,170111,212831,475330,218,W.W. Norton & Company (NYC),2005-01-01,Fight Club,4.034411
8815,51501,Strange Case of Dr. Jekyll and Mr. Hyde,Robert Louis Stevenson,eng,3.81,4632,21560,102150,139118,91294,358754,240,W. W. Norton & Company,2003-01-01,Strange Case of Dr. Jekyll and Mr. Hyde,3.779041
925,4395,The Grapes of Wrath,John Steinbeck,eng,3.96,29408,49440,128216,221271,288934,717269,455,Penguin Books,2002-01-01,The Grapes of Wrath,3.902242
57876,618291,"Slaughterhouse-Five, or The Children's Crusade",Kurt Vonnegut Jr.,eng,4.08,28782,53936,182544,368191,460959,1094412,205,Delacorte Press,1994-01-01,This 25th anniversary edition of Slaughterhous...,4.016461
17672,118229,The Princess Bride: S. Morgenstern's Classic T...,William Goldman,eng,4.26,14780,24694,100336,222948,389388,752146,399,Ballantine Books,1998-01-01,The Princess Bride: S. Morgenstern's Classic T...,4.130298
7970,45503,El Alquimista: Edicion Illustrada: Edicion Ill...,Paulo Coelho,eng,3.87,96626,161716,387535,570564,740493,1956934,192,Rayo,2007-01-01,El Alquimista: Edicion Illustrada: Edicion Ill...,3.854797
71664,839840,Never Let Me Go,Kazuo Ishiguro,eng,3.82,11976,34532,106191,164078,131358,448135,263,Knopf Canada,2005-01-01,Hailsham seems like a pleasant English boardin...,3.789482
94899,1297872,The Odyssey of Homer,Homer,eng,3.77,33512,73210,209615,268290,258953,843580,390,Harper Perennial Modern Classics,2007-01-01,The most eloquent translation of Homer's epic ...,3.761849
97228,1362949,Into Thin Air: A Personal Account Of The Evere...,Jon Krakauer,eng,4.18,8576,11452,53221,139716,170124,383089,293,Macmillan,1997-01-01,A bank of clouds was assembling on the not-so-...,4.005513
901,4255,Harry Potter and the Philosopher's Stone,J.K. Rowling,eng,4.47,108208,130321,567498,1513308,4268678,6588013,223,Bloomsbury Publishing PLC,2004-01-01,Harry Potter and the Philosopher's Stone,4.443492
1017,4916,Angela's Ashes,Frank McCourt,eng,4.11,9749,21707,85597,186948,213983,517984,224,Simon & Schuster,1998-01-01,Angela's Ashes,3.988864
71175,833387,The Pelican Brief,John Grisham,eng,4.00,2919,13772,82984,140593,120704,360972,432,Arrow,1993-01-01,"Two Supreme Court Justices are dead, their mur...",3.892128
12,21,A Short History of Nearly Everything,Bill Bryson,eng,4.21,5140,9367,38064,94040,129555,276166,544,Broadway Books,2004-01-01,A Short History of Nearly Everything,3.985655

In [17]:
above_average.head(20)

,BookID,BookTitle,Authors,Language,AverageRating,1StarRatingCount,2StarRatingCount,3StarRatingCount,4StarRatingCount,5StarRatingCount,TotalRatingCount,PageCount,Publisher,PublishYear,Description,weighted
76247,912224,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,eng,4.62,22122,33357,156474,532749,1963450,2708152,759,Arthur A. Levine Books,2007-01-01,"Readers beware. The brilliant, breathtaking co...",4.546183
69933,818056,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,eng,4.62,22089,33318,156299,532119,1960662,2704487,607,Bloomsbury Publishing Plc/Raincoast Books,2007-01-01,Harry is waiting in Privet Drive. The Order of...,4.546091
19568,136251,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,eng,4.62,21838,33025,154874,526196,1932990,2668923,759,Arthur A. Levine Books / Scholastic Inc.,2007-01-01,Harry Potter and the Deathly Hallows (Harry Po...,4.545189
11302,71643,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,eng,4.62,21818,32985,154564,524967,1927239,2661573,816,Arthur A. Levine Books,2007-01-01,Harry Potter and the Deathly Hallows (Harry Po...,4.545000
145004,3106176,Harry Potter and the Prisoner of Azkaban,J.K. Rowling,eng,4.57,11793,26600,203373,662552,1870610,2774928,468,Bloomsbury Publishing PLC,1999-01-01,Harry Potter's third year at Hogwarts is full ...,4.501888
94356,1286752,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,eng,4.57,10739,25533,198858,646506,1813195,2694831,317,Bloomsbury Publishing PLC,2004-01-01,Harry Potter's third year at Hogwarts is full ...,4.500033
70017,819073,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,eng,4.57,10560,25366,197722,642462,1798499,2674609,317,Bloomsbury,1999-01-01,Harry Potter's third year at Hogwarts is full ...,4.499548
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,eng,4.57,10128,24849,194848,630534,1749958,2610317,435,Scholastic Inc.,2004-01-01,Harry Potter and the Prisoner of Azkaban (Harr...,4.497962
71708,840699,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,eng,4.57,10205,25687,162056,565027,1580517,2343492,608,Bloomsbury Publishing,2006-01-01,It is Harry Potter's sixth year at Hogwarts Sc...,4.490540
58801,633308,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,eng,4.57,10138,25630,161771,563989,1576521,2338049,831,Large Print Press,2007-01-01,The war against Voldemort is not going well; e...,4.490373
21388,155104,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,eng,4.57,9943,25384,160415,558314,1553748,2307804,607,Bloomsbury Publishing,2005-01-01,Harry Potter and the Half-Blood Prince (Harry ...,4.489430
14419,93124,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,eng,4.57,9938,25375,160361,558101,1552880,2306655,607,Bloomsbury Publishing,2005-01-01,Harry Potter and the Half-Blood Prince (Harry ...,4.489393
11172,70367,Harry Potter and the Half-blood Prince (Harry ...,J.K. Rowling,eng,4.57,9910,25336,160077,556874,1548130,2300327,652,Turtleback Books,2006-01-01,Harry Potter and the Half-blood Prince (Harry ...,4.489193
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,eng,4.57,9896,25317,159960,556485,1546466,2298124,652,Scholastic Inc.,2006-01-01,Harry Potter and the Half-Blood Prince (Harry ...,4.489123
73135,862710,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,eng,4.56,9734,24718,180924,617499,1653139,2486014,796,Raincoast Books,2004-01-01,Harry Potter is midway through his training as...,4.485586
5,6,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,eng,4.56,9419,24282,178419,606800,1612165,2431085,734,Scholastic,2002-01-01,Harry Potter and the Goblet of Fire (Harry Pot...,4.484059
114012,1885731,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,eng,4.47,113129,134792,585139,1566042,4440106,6839208,332,Bloomsbury Publishing PLC,1998-01-01,Harry Potter thinks he is an ordinary boy - un...,4.444432
94739,1294624,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,eng,4.47,111946,133687,581263,1555046,4406269,6788211,224,Bloomsburry,1998-01-01,When a letter arrives for unhappy but ordinary...,4.444246
72271,848654,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,eng,4.47,111023,132906,577952,1545821,4377168,6744870,223,Bloomsbury Publishing,1997-01-01,Harry Potter thinks he is an ordinary boy unti...,4.444087
69934,818060,Harry Potter and the Philosopher's Stone,J.K. Rowling,eng,4.47,110971,132872,577814,1545364,4375719,6742740,336,Raincoast Book Distribution,2004-01-01,Harry Potter's life is miserable. His parents ...,4.444079

In [19]:
above_average = above_average.drop_duplicates('BookTitle')[['BookTitle', 'Authors', 'Publisher', 'Description']]

In [24]:
above_average.head(50)

,BookTitle,Authors,Publisher,Description
76247,Harry Potter and the Deathly Hallows (Harry Po...,J.K. Rowling,Arthur A. Levine Books,"Readers beware. The brilliant, breathtaking co..."
145004,Harry Potter and the Prisoner of Azkaban,J.K. Rowling,Bloomsbury Publishing PLC,Harry Potter's third year at Hogwarts is full ...
94356,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling,Bloomsbury Publishing PLC,Harry Potter's third year at Hogwarts is full ...
71708,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling,Bloomsbury Publishing,It is Harry Potter's sixth year at Hogwarts Sc...
11172,Harry Potter and the Half-blood Prince (Harry ...,J.K. Rowling,Turtleback Books,Harry Potter and the Half-blood Prince (Harry ...
73135,Harry Potter and the Goblet of Fire (Harry Pot...,J.K. Rowling,Raincoast Books,Harry Potter is midway through his training as...
114012,Harry Potter and the Philosopher's Stone (Harr...,J.K. Rowling,Bloomsbury Publishing PLC,Harry Potter thinks he is an ordinary boy - un...
69934,Harry Potter and the Philosopher's Stone,J.K. Rowling,Raincoast Book Distribution,Harry Potter's life is miserable. His parents ...
27322,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,Turtleback Books,Harry Potter and the Sorcerer's Stone (Harry P...
12248,Harry Potter and the Sorcerer's Stone,J.K. Rowling,Arthur A. Levine Books / Scholastic Inc.,Harry Potter and the Sorcerer's Stone
111215,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,Bloomsbury,There is a door at the end of a silent corrido...
73050,Harry Potter and the Order of the Phoenix,J.K. Rowling,Bloomsbury,Dumbledore lowered his hands and surveyed Harr...
162989,The Help,Kathryn Stockett,Amy Einhorn Books/G.P. Putnam's Sons,Librarian's note: An alternate cover edition c...
96184,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,Large Print Press,Ever since Harry Potter had come home for the ...
101556,"A Game of Thrones (A Song of Ice and Fire, #1)",George R.R. Martin,Meisha Merlin,Here is the first volume in George R. R. Marti...
70260,Harry Potter and the Chamber of Secrets,J.K. Rowling,Bloomsbury UK,This is a follow up to Harry Potter and the Ph...
131337,The Name of the Wind (The Kingkiller Chronicle...,Patrick Rothfuss,Orion Publishing Group,"Told in Kvothe's own voice, this is the tale o..."
89661,"A Storm of Swords (A Song of Ice and Fire, #3)",George R.R. Martin,Bantam Spectra,Here is the third volume in George R. R. Marti...
110540,"The Return of the King (Lord of the Rings, #3)",J.R.R. Tolkien,Ballantine Books,Cat#/price on cover: 27260/$2.50Editions with ...
92058,"The Return of the King (The Lord of the Rings,...",J.R.R. Tolkien,Houghton Mifflin,In the third volume of The Lord of the Rings t...
58602,The Return of the King (The Lord of the Rings #3),J.R.R. Tolkien,Turtleback Books,Sauron and Gandalf the Grey battle for possess...
137427,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,Scholastic Press,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...
115568,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. Tolkien,HarperCollins,The first ever illustrated paperback of part o...
92617,The Fellowship of the Ring,J.R.R. Tolkien,Harper Collins - Voyager Classics,"One Ring to rule them all, One Ring to find th..."
114611,The Book Thief,Markus Zusak,Random House Group Ltd.,It is 1939. Nazi Germany. The country is holdi...
132189,The Lord of the Rings,J.R.R. Tolkien,HarperCollins Publishers Ltd,"Classics in the genre, J.R.R. Tolkien's defini..."
118985,"The Two Towers (The Lord of the Rings, #2)",J.R.R. Tolkien,Unwin Paperbacks,"Following THE FELLOWSHIP OF THE RING, a second..."
96305,The Lord Of The Rings,J.R.R. Tolkien,Unwin Hyman,"One Ring to rule them all, One Ring to find th..."
63409,"The Lord of the Rings (The Lord of the Rings, ...",J.R.R. Tolkien,Mariner Books,"The novel of the century, now with new movie t..."
3103,The Lord of the Rings Millennium Edition Boxed...,J.R.R. Tolkien,Houghton Mifflin,The Lord of the Rings Millennium Edition Boxed...
26,The Lord of the Rings Box Set,J.R.R. Tolkien,Penguin Books,The Lord of the Rings Box Set
91288,"The Wise Man's Fear (The Kingkiller Chronicle,...",Patrick Rothfuss,DAW Books,“There are three things all wise men fear: the...
102091,A Thousand Splendid Suns,Khaled Hosseini,Penguin,After 103 weeks on the New York Times bestsell...
131338,The Wise Man's Fear (The Kingkiller Chronicle...,Patrick Rothfuss,Gollancz,Sequel to the extraordinary THE NAME OF THE WI...
161603,To Kill a Mockingbird,Harper Lee,Perfection Learning,"Featuring a new introduction by the author, th..."
126221,"To Kill a Mockingbird (To Kill a Mockingbird, #1)",Harper Lee,Warner Books,The unforgettable novel of a childhood in a sl...
80433,To Kill A Mockingbird,Harper Lee,Petersen,The unforgettable novel of a childhood in a sl...
89711,A Clash Of Kings,George R.R. Martin,Voyager Books,A comet the color of blood and flame cuts acro...
15406,The Kite Runner,Khaled Hosseini,Riverhead Books,The Kite Runner
14256,"A Clash of Kings (A Song of Ice and Fire, #2)",George R.R. Martin,Bantam Spectra,"A Clash of Kings (A Song of Ice and Fire, #2)"
2095,"A Clash of Kings (A Song of Ice and Fire, #2)",George R.R. Martin,Bantam,"A Clash of Kings (A Song of Ice and Fire, #2)"
163773,"Harry Potter Adult Boxed Set (Harry Potter, #1-7)",J.K. Rowling,Bloomsbury Publishing PLC,"A boxed set, including the titles 'Harry Potte..."
121284,The Battle of the Labyrinth (Percy Jackson and...,Rick Riordan,Hyperion Books for Children,Percy Jackson isn't expecting freshman orienta...
40324,The Giving Tree,Shel Silverstein,HarperCollins Publishers,The Giving Tree
148677,Hobbitten,J.R.R. Tolkien,Gyldendal,"Tolkiens klassiker om hobbitten Bilbo Sækker, ..."
130619,The Hobbit Or There And Back Again,J.R.R. Tolkien,Ballantine Books,The Hobbit Or There And Back Again
125653,The Hobbit: The Enchanting Prelude To The Lord...,J.R.R. Tolkien,Ballantine Books,"""In a hole in the ground there lived a hobbit...."
119983,The Hobbit,J.R.R. Tolkien,HarperCollins,The great modern classic and prelude to The Lo...
75480,The Annotated Hobbit,J.R.R. Tolkien,Unwin Hyman,"For readers throughout the world, The Hobbit s..."
71580,"The Hobbit Or, There and Back Again",J.R.R. Tolkien,Unwin Hyman,"The Hobbit Or, There and Back Again"

=======================================================================================================================